[package]
name = "rusTar"
version = "0.1.0"
authors = ["b4nk3r"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
tar = "0.4.26"
flate2 = "1.0.14"
